// 此文件保留用于向后兼容，所有工具函数已迁移到 src/utils/ 目录
// 请使用新的导入路径：import { ... } from './utils';

export {
  parseVocabulary,
  generateStableId,
  isPhonetic,
  hasChinese,
  isPartSpeech,
  wordKey,
  matchWordKey,
  highlightDiff,
  pairDiffPositions,
  shuffleArray,
  sample,
  chunk,
  seededRng,
  hashSeed,
  generateQuiz,
  calculateScore,
  getScoreRating,
  generateSeed,
  encodeChallenge,
  decodeChallenge,
  buildChallengeQuestions,
  createInitialSrs,
  applyReview,
  isDue,
  selectDueWords,
  pickMistakes,
  FEEDBACK_QUALITY,
  planUnitsForStage,
  unitProgress,
  recordActivity,
  computeStreak,
  totalCorrect,
  totalAnswered,
  overallAccuracy,
  evaluateAchievements,
  ACHIEVEMENT_DEFS,
  buildDailySummaries,
  weeklyComment,
  groupConfusionPairs,
  exportBundle,
  importBundle,
  downloadBundle,
  readBundleFromFile,
} from './utils/index';

export type { ChallengeData } from './utils/index';
